# Generated by Django 2.0.13 on 2019-05-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Implementodep',
            new_name='Post',
        ),
    ]
