# Generated by Django 2.0.13 on 2019-05-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190515_0207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Implementodep',
        ),
    ]
